const FRERE_COLUMNS = {
    NOM: 1,
    PRENOM: 2,
    MAIL: 3,
    TELEPHONE: 4,
    ADMIN: 5
};

const MAGASIN_COLUMNS = {
    NOM: 1,
    ADRESSE: 2,
    QUARTIER: 3,
    CODEPOSTAL: 4,
    VILLE: 5,
    TYPE: 6,
    DELAISRECUPERATION: 7,
    TELEPHONE: 8
};

const TIRELIRE_COLUMNS = {
    MAGASIN: 1,
    DATE_DEPOT: 2,
    DATE_RETRAIT: 3,
    MONTANT: 4,
    RECUPERE: 5,
    PERDU: 6,
    RESPONSABLE: 7,
    ID_EVENT: 8
};