const FRERE_COLUMNS = {
    NOM: 1,
    PRENOM: 2,
    MAIL: 3,
    TELEPHONE: 4,
    ROLE: 5
};

const MAGASIN_COLUMNS = {
    NOM: 1,
    ADRESSE: 2,
    QUARTIER: 3,
    CODE_POSTAL: 4,
    VILLE: 5,
    TYPE: 6,
    DELAISRECUPERATION: 7,
    TELEPHONE: 8
};

const TIRELIRE_COLUMNS = {
    MAGASIN: 1,
    DATE_DEPOT: 2,
    DATE_RETRAIT: 3,
    MONTANT: 4,
    RECUPERE: 5,
    PERDU: 6,
    RESPONSABLE: 7,
    ID_EVENT: 8
};

const REPONSES_FORMULAIRE = {
    HORODATEUR: 1,
    RECUPEREE: 2,
    PERDUE_VOLEE: 3,
    REPROGRAMMER: 4,
    TRANSFERER: 5,
    LISTE_FRERES: 6,
    DATE_REPROGRAMMATION: 7,
    CONTENU_CONNU: 8,
    MONTANT_RECUPERE: 9,
    EMAIL: 10,
    ID_EVENEMENT: 11
};