---
name: Deploy Script

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - develop
      - add_workflow

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Super-Linter
        uses: super-linter/super-linter@v6.5.1
        env:
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Deploy Sheets project to Google Apps Script
        uses: Mayu-mic/google-apps-script-action@v1
        with:
          clasprc: ./Google_Sheets/.clasp.json
          scriptId: ${{ secrets.SCRIPT_ID_GOOGLE_SHEETS }}
          command: "push"
          sourceRootDir: ./Google_Sheets

      - name: Deploy Forms project to Google Apps Script
        uses: Mayu-mic/google-apps-script-action@v1
        with:
          clasprc: ./Google_Forms/.clasp.json
          scriptId: ${{ secrets.SCRIPT_ID_GOOGLE_FORMS }}
          command: "push"
          sourceRootDir: ./Google_Forms
